name: ShopSystem
version: '${project.version}'
main: dk.shadow.shopsystem.ShopSystem
api-version: 1.19
authors: [ Shad0wsense ]
description: A shopSysttem
website: Cutekat.dk
commands:
  shopsystem:
    aliases: [shop]
    description: Command for shopsystem